### ISSUE TITLE
Test conformance with the spec

### ISSUE THREAD

**Issue by scothis** [servicebinding/runtime#134]
The service binding spec has a conformance test suite being built over in https://github.com/servicebinding/conformance/. We should start running the conformances tests as part of our in-cluster acceptance tests. When we find failing conformances test, we'll need to investigate if the implementation or the test are out of alignment with the spec.

**Comment by baijum** [comment]
Are we going to run a nightly job against the main branch? I think no need to run for every PR by default. If necessary, we could run it in a PR, based on a certain label, say, `conformance-tests-required`. If the PR author or maintainer adds that label, let the job gets triggered. 

cc. @sadlerap

**Comment by scothis** [comment]
I would imagine we add the conformances tests as part of our current acceptance tests since we already have a cluster spun up with the controller installed. That already runs for every pushed commit/pr against (too?) many versions of k8s.

If/when that becomes too heavy, we can back it off and run the full suite less often at the risk of accepting that regressions will happen on main.

**Comment by sadlerap** [comment]
I think for now we should run conformance tests on all PRs.  We can always revisit our testing strategy once it becomes more and more complete; perhaps we could run only the parts of the test suite that are determined to be impacted by a PR?

**Comment by sadlerap** [comment]
Initial work for this was implemented in #147, but there's still more work to do.  The conformance test suite doesn't (yet) check for full specification conformance.

**Comment by scothis** [comment]
We're testing against the conformance suite
